### ISSUE TITLE
capture doesn't work

### ISSUE THREAD

**Issue by ghost** [wg-perception/object_recognition_core#17]
Hi,
I'm trying to use ORK with ROS Groovy, and I have several issues.
I'm following this tuto : http://wg-perception.github.io/capture/index.html
using an Asus Xtion pro live sensor.

Firstly, I can't use capture with no "-i" argument, the program throws a segmentation fault.
here is what I get :
$ rosrun object_recognition_capture capture -o object.bag -m
Registration? 1
Sync? 0
1. device on bus: 1 @ 6 with serial number:   PrimeSense : PrimeSense Device
Time diff max: 16.8667
Registered:on Supported: 1
Setting registration on
Setting sync off
Segmentation fault (core dumped)

So i decided to make an ORB template of the inverted dot pattern provided on the web page. It seems to works, when I run orb_track. But it don't show the 'xyz' axis attached to the plan, is that OK? Here are results of 
rosrun object_recognition_capture orb_track --track_directory fiducial_dot_pattern_bigger/ --track_show_matches_enable

![screenshot from 2013-06-21 13 22 19](https://f.cloud.github.com/assets/4750512/686768/fe8f7236-da64-11e2-82ee-2db27910f8f3.png)
![screenshot from 2013-06-21 13 22 35](https://f.cloud.github.com/assets/4750512/686767/eb769526-da64-11e2-94da-f0d17e01bee6.png)

My second problem is when I try to capture an object with this orb template.
When I run 
rosrun object_recognition_capture capture -o object.bag -m -i fiducial_dot_pattern_bigger/
the mask is all black, and the xyz axis still don't appear in the 'pose' window. but matches looks OK for the orb template.
I don't get anything similar to the picture of the tuto : http://wg-perception.github.io/capture/_images/capture.gif
When I turn the board, nothing appends but the update of the display, the program don't stop after a full rotation and I have no output file.

Am I doing something wrong? Is there a solution (I guess there is!)?
Thank you for your help,
I hope this is the good place for submitting that kind of issues.

Jules

(excuse if my English is not that good :) )

**Comment by fivef** [comment]
Same for me. I just don't get the axes in capture mode.
