### ISSUE TITLE
MacOSX Installation Problem

### ISSUE THREAD

**Issue by CptMonac** [wg-perception/object_recognition_core#21]
While trying to install the Object Recognition Kitchen without ROS, I ran into the following error, about boost_python. The Boost Library is already installed on the computer (using brew install boost under /usr/local/include). However, I get an error about not finding static Boost Libraries. Any help would be much appreciated.

-- +++ processing catkin package: 'ecto_openni'
-- ==> add_subdirectory(ecto_openni)
CMake Error at /Applications/CMake 2.8-12.app/Contents/share/cmake-2.8/Modules/FindBoost.cmake:1111 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.54.0

  Boost include path: /usr/local/include

  Could not find the following static Boost libraries:

          boost_python

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.

-- OpenNI NOT found.
-- Will not be building ecto_openni, as openni has not been found.
-- +++ processing catkin package: 'ecto_ros'
-- ==> add_subdirectory(ecto_ros)
CMake Error at /Users/nyannier/Documents/EarthShake/ork/build/devel/share/catkin/cmake/catkinConfig.cmake:72 (find_package):
  Could not find a package configuration file provided by "geometry_msgs"
  with any of the following names:

    geometry_msgsConfig.cmake
    geometry_msgs-config.cmake

  Add the installation prefix of "geometry_msgs" to CMAKE_PREFIX_PATH or set
  "geometry_msgs_DIR" to a directory containing one of the above files.  If
  "geometry_msgs" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  ecto_ros/CMakeLists.txt:6 (find_package)

**Comment by vrabaud** [comment]
a lot has happened since then, especially OSX compilation fixes. Please re-open if you still have issues.
