### ISSUE TITLE
Overall Problem with ORK

### ISSUE THREAD

**Issue by xMutzelx** [wg-perception/object_recognition_core#40]
Hello Community,
I have a big problem with ORK. I already made different posts in Tabletop [#27](https://github.com/wg-perception/tabletop/issues/27#issuecomment-220563303) Linemod [#31](https://github.com/wg-perception/linemod/issues/31#issuecomment-220921503) and Capture [#27](https://github.com/wg-perception/capture/issues/27#issuecomment-220528084).
Hopefully this big post will fix those problems. 

I tried different fixes already:
- I tried older versions of ORK (git checkout xxxx)
- I installed Ubuntu 14.04 completly fresh and just followed the tutorial.
- I installed everything completly fresh on different computers with different hardware
- Several forum posts did not fix those problems
- ORK installation from source and with rosinstaller

I am using Ubuntu 14.04, Ros Indigo and Python 2.7.6. 

My installation steps are:
- Install Ubuntu 14.04 completly new
- sudo apt-get update && sudo apt-get upgrade
- Ros Indigo Installation: http://wiki.ros.org/indigo/Installation/Ubuntu 
      - Desktop full install
- Workspace init: http://wiki.ros.org/catkin/Tutorials/create_a_workspace
- Installation of Openni: http://blog.justsophie.com/installing-kinect-nite-drivers-on-ubuntu-14-04-and-ros-indigo/
     - Plus installation of rgbd_launch in catkin_ws
- Installation of ORK and CouchDB: http://wg-perception.github.io/object_recognition_core/install.html#install
- Tests and always the same errors

Thank you very much for you help. I really appreciate it.

**Comment by hris2003** [comment]
Hi,

From my poor memory, that error related to boost happens when one or more
topics were not available. Did you check that?

It might be interesting that you could provide a rosbag of your capture
data so that we can check it on our computer.

Regards,
Ha Dang.

**Comment by xMutzelx** [comment]
Thank you for your reply. Here is a 5 sec bag file with all ros topics in it. I hope the download link works: [WeTransfer](https://we.tl/lRv1BNVtp1)

Yes I checked the relevant topics:
**Tested topics:**
/camera/depth_registered/camera_info
/camera/depth_registered/image_raw
/camera/rgb/camera_info
/camera/rgb/image_rect_color

**Commands:**
rostopic list
rostopic hz /topic_name 
rostopic echo /topic_name

My outputs are here: [link ](https://github.com/wg-perception/linemod/issues/31#issuecomment-220921503)

**Comment by xMutzelx** [comment]
I fixed my problem! It was very complicated but finally it works.
My solution:
Follow the installation tutorial:
**NOTE: Do not download Linemod!**
Change versions of:
```
1. visualization: f072ccf
2. tod: 0.5.5
3. transparent: 75d7663
4. reconstruct: 8adb948
5. core: fb3b3df
6. capture: 0.3.1
7. renderer: 3af6195
8. tabletop: 7d49e3e
```

Combine all of these solutions:
[Nr.1](https://github.com/wg-perception/ork_renderer/pull/9/files)
[Nr.2](https://groups.google.com/forum/#!msg/object-recognition-kitchen/aS9YlKJxOnc/siFhK4uKDwAJ)
[Nr.3](https://github.com/wg-perception/ork_renderer/pull/9/files)

After the changes `catkin_make`

The last steps are:
```
1. Download Linemod and change version to: 3b8ddca
2. catkin_make
```

You have to delete your complete database. Default is OSMesa and I changed it to GLUT. If you have learned meshes with OSMesa it wont work with GLUT. 
I can write a more detailed answer if needed.

**Comment by TrinhTUHH** [comment]
I got this error while catkin_make:
Package version "f072ccf" does not follow version conventions
