### ISSUE TITLE
Finding planes 

### ISSUE THREAD

**Issue by ahuo002** [wg-perception/object_recognition_core#52]
No topic under OrkTable in the rviz after 'rosrun object_recognition_core detection -c `rospack find object_recognition_tabletop`/conf/detection.table.ros.ork'.
The same as OrkObject...
why? It seems erverything is Ok, I did step by step, Install,Tutorials...

**Comment by hris2003** [comment]
Without input sample (i.e. Do you have a rosbag of the scene you're using to test tabletop?), we can not be of help here.

**Comment by ahuo002** [comment]
@hris2003 step1, tsep2... then "rosrun object_recognition_core detection -c rospack find object_recognition_tabletop/conf/detection.table.ros.ork". Could I see the topic "table_array" or something else, if I run "rostopic list". But nothing about "detection".

**Comment by hris2003** [comment]
What do you get with `rostopic echo /table_array` ?

**Comment by ahuo002** [comment]
@hris2003 WARNING: topic [/table_array] does not appear to be published yet

**Comment by hris2003** [comment]
And the 3D cloud? Can you see it in rviz?

**Comment by ahuo002** [comment]
@hris2003 Yes. 
I can find "table_array" in the codes, I don't how the node to publish this topic?

**Comment by hris2003** [comment]
What are you trying to do with tabletop? If you want to understand how it works, I recommend you to read about ecto (http://plasmodic.github.io/ecto/) and other hyperlinks in the main page (https://wg-perception.github.io/object_recognition_core/).

**Comment by ahuo002** [comment]
@hris2003 Thank you very much, I will read those codes. But now I just want to use it.

**Comment by hris2003** [comment]
Well, if you want to use it, then just follow the tutorial of tabletop (http://wg-perception.github.io/tabletop/index.html#tabletop). Which part of it bugs you? I would recommend you to focus on the parameters explanation part (http://wg-perception.github.io/tabletop/index.html#manage-tabletop-s-input-parameters).

**Comment by ahuo002** [comment]
@hris2003 Thank you, I will follow the tutorial of tabletop, than read about ecto.

**Comment by ahuo002** [comment]
@hris2003 I know what is wrong. I should modify the file of "detection.table.ros.ork" .(/opt/ros/indigo/share/object_recognition_tabletop/conf/). 
{ (http://wg-perception.github.io/tabletop/index.html#tabletop) }

**Comment by hris2003** [comment]
Great! I close the issue then.
