### ISSUE TITLE
Error in running object_recognition_core

### ISSUE THREAD

**Issue by zaclizer** [wg-perception/object_recognition_core#7]
Having installed from the ROS Groovy repositories, I run into this error when attempting to view the usage for object_recognition_core capture:

$ rosrun object_recognition_core detection -h
Traceback (most recent call last):
  File "/opt/ros/groovy/lib/object_recognition_core/detection", line 3, in <module>
    from object_recognition_core.utils.training_detection_args import common_create_parser, read_arguments_detector
  File "/opt/ros/groovy/lib/python2.7/dist-packages/object_recognition_core/utils/training_detection_args.py", line 5, in <module>
    from object_recognition_core.boost.interface import ObjectDbParameters
ImportError: No module named interface

Looking in
$ /opt/ros/groovy/lib/python2.7/dist-packages/object_recognition_core/boost

the directory appears to be empty apart from an empty init file.

**Comment by Tatosx2** [comment]
Hello,
I am running the following command:
rosrun object_recognition_core object_add.py -n coke -d "A universal can of coke" 
and I am getting this error as a result (I've tried recreating the said files to no avail):
Traceback (most recent call last):
  File "/home/tsquared/ork/src/object_recognition_core/apps/dbscripts/object_add.py", line 6, in <module>
    from object_recognition_core.db import models
  File "/home/tsquared/ork/src/object_recognition_core/python/object_recognition_core/db/__init__.py", line 3, in <module>
    from object_recognition_core.boost.interface import ObjectDbParameters, ObjectDbTypes, Documents, Models, Document
ImportError: No module named interface
Thanks in advance!

**Comment by awesomebytes** [comment]
Explaining a bit more of your setup may help understand your problem.

What Ubuntu version, what ROS version, why aren't you using the binary
packages instead of a source code install.

**Comment by Tatosx2** [comment]
Sorry my bad, ROS: Kinetic, Ubuntu 16.04.
I temporarily "fixed" it by removing the indicated lines of code. Why should I be using the binary packages?
I've now got a different error when I run:
rosrun object_recognition_core detection -c  `rospack find object_recognition_linemod`/conf/detection.ros.ork
I then get:
Traceback (most recent call last):
  File "/home/tsquared/ork/src/object_recognition_core/apps/detection", line 6, in <module>
    from object_recognition_core.pipelines.plasm import create_plasm
  File "/home/tsquared/ork/src/object_recognition_core/python/object_recognition_core/pipelines/plasm.py", line 4, in <module>
    from object_recognition_core.io.voter import VoterBase
  File "/home/tsquared/ork/src/object_recognition_core/python/object_recognition_core/io/voter.py", line 5, in <module>
    from object_recognition_core.ecto_cells.voter import Aggregator as AggregatorCpp
ImportError: No module named voter

**Comment by awesomebytes** [comment]
Well, it very much looks like your setup is broken.

The binary packages... are tested and used by other people, so, they should work.

Give them a try:
```bash
sudo apt-get install ros-kinetic-object-recognition-*
```

And use a shell without your local workspace sourced to be sure you use those ones.

**Comment by Tatosx2** [comment]
Wow mate, thanks a lot, had no idea this existed,not sure as to how I was not aware. :)
How would I go about installing this?
So I just install these generically and make a new catkin work-space and go from there?

**Comment by awesomebytes** [comment]
> How would I go about installing this?

```bash
sudo apt-get install ros-kinetic-object-recognition-*
```

> So I just install these generically and make a new catkin work-space and go from there?

Yeah, open a new shell, where you only have source `source /opt/ros/kinetic/setup.bash` and just run your command again: 

```bash
rosrun object_recognition_core object_add.py -n coke -d "A universal can of coke"
```
